ShoppingCart/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCartInterfaces.IUnitOfWork;
using ShoppingCartModels.DbModels;
using ShoppingCartModels.ViewModels;
using System.Linq;

namespace ShoppingCart.Areas.Admin.Controllers
{

    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        public IActionResult Manage()
        {
            try
            {
                CategoryViewModel model = new CategoryViewModel();
                model.Categories = _unitOfWork.Category.GetAll().Result.OrderBy(x => Convert.ToInt32(x.DisplayOrder));
                //TempData["Success"] = $"Categories Recived {model.Categories.Count()}"; 
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpGet]
        public async Task<IActionResult> CreateOrEdit(int? id)
        {
            try
            {
                //Create
                if(id == null)
                {
                    ViewData["Title"] = "Create";
                    ViewData["button-color"] = "btn btn-primary";
                    return View();
                }
                //Edit
                else
                {
                    ViewData["Title"] = "Update";
                    ViewData["button-color"] = "btn btn-success";
                    CategoryViewModel model = new CategoryViewModel();
                    model.Category = await _unitOfWork.Category.Find(Convert.ToInt32(id));
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(CategoryViewModel model)
        {
            try
            {
                int res = 0;
                //TempData["Success"] = $"{model.Category.Name} - Category added";
                if (model.Category.Id > 0)
                {
                    res = await _unitOfWork.Category.Update(model.Category);
                }
                else
                {
                    res = await _unitOfWork.Category.Add(model.Category);
                    
                }

                if(res == 0) TempData["Error"] = $"{model.Category.Name} - Category didn't updated";               
                else TempData["Success"] = $"{model.Category.Name} - Category updated";               
                return RedirectToAction("Manage");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                ViewData["Title"] = "Details";
                ViewData["button-color"] = "btn btn-warning";
                CategoryViewModel model = new CategoryViewModel();
                model.Category = await _unitOfWork.Category.Find(Convert.ToInt32(id));
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                ViewData["Title"] = "Delete";
                ViewData["button-color"] = "btn btn-danger";
                CategoryViewModel model = new CategoryViewModel();
                model.Category = await _unitOfWork.Category.Find(Convert.ToInt32(id));
                return View(model);

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CategoryViewModel model)
        {
            try
            {
                int res = await _unitOfWork.Category.Delete(model.Category);
                if (res == 0) TempData["Error"] = $"{model.Category.Name} - Category didn't Deleted";
                else TempData["Success"] = $"{model.Category.Name} - Category Deleted";
                return RedirectToAction("Manage");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
    }
}

ShoppingCart/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCartInterfaces.IUnitOfWork;
using ShoppingCartModels.ViewModels;

namespace ShoppingCart.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Manage()
        {
            try
            {
                OrderViewModel model = new OrderViewModel
                {
                    Orders = await Task.Run(() => _unitOfWork.Order.Get().Result
                                     .OrderByDescending(x => x.OrderDate).ToList())
                };
                TempData["Success"] = "Orders fetched successfully";
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");                
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int productId)
        {
            try
            {
                if(productId < 0) TempData["Error"] = "Wrong Product Id";
                
                OrderViewModel model = new OrderViewModel
                {
                    Order = await Task.Run(() => _unitOfWork.Order.Find(productId))
                };
                TempData["Success"] = "Order fetched successfully";
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");                
            }
        }


        [HttpPost]
        public async Task<IActionResult> UpdateOrder(OrderViewModel model)
        {
            try
            {
                if (model.Order.OrderStatus is null)
                {
                    TempData["Error"] = "Please select status";
                    return RedirectToAction("Details", model);
                }
                var response = await Task.Run(() => _unitOfWork.Order.Update(model.Order));
                if(response > 0) TempData["Success"] = "Order Updated successfully";
                else TempData["Error"] = "Order didn't Updated";
                return RedirectToAction(nameof(Manage));
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");                
            }
        }
    }
}

ShoppingCart/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ShoppingCartInterfaces.IUnitOfWork;
using ShoppingCartModels.DbModels;
using ShoppingCartModels.ViewModels;
using System.Web.WebPages.Html;

namespace ShoppingCart.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _web;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment web)
        {
            this._unitOfWork = unitOfWork;
            this._web = web;
        }
        public IActionResult Manage()
        {
            try
            {
                ProductViewModel model = new ProductViewModel();
                model.Products = _unitOfWork.Product.GetProducts()
                    .Result.OrderBy(x => Convert.ToInt32(x.DisplayOrder));
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpGet]
        public async Task<IActionResult> CreateOrEdit(int? id)
        {
            try
            {
                ViewBag.Categories = await _unitOfWork.Category.GetAll();
                //Create
                if (id == null)
                {
                    ViewData["Title"] = "Create";
                    ViewData["button-color"] = "btn btn-primary";
                    return View();
                }
                //Edit
                else
                {
                    ViewData["Title"] = "Update";
                    ViewData["button-color"] = "btn btn-success";
                    ProductViewModel model = new ProductViewModel
                    {
                        Product = await _unitOfWork.Product.Find(Convert.ToInt32(id))                        
                    };
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(ProductViewModel model)
        {
            try
            {
                int res = 0;
                string folderPath = await UploadedFile(model);
                model.Product.ImageUrl = folderPath;

                if (model.Product.Id > 0) res = await _unitOfWork.Product.UpdateProducts(model.Product);
                else res = await _unitOfWork.Product.Add(model.Product);
                
                if (res == 0) TempData["Error"] = $"{model.Product.Name} - Product didn't updated";
                else TempData["Success"] = $"{model.Product.Name} - Product updated";
                
                return RedirectToAction("Manage");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                ViewData["Title"] = "Details";
                ViewData["button-color"] = "btn btn-warning";
                ProductViewModel model = new ProductViewModel();
                model.Product = await _unitOfWork.Product.Find(Convert.ToInt32(id));
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                ViewData["Title"] = "Delete";
                ViewData["button-color"] = "btn btn-danger";
                ProductViewModel model = new ProductViewModel();
                model.Product = await _unitOfWork.Product.Find(Convert.ToInt32(id));
                return View(model);

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ProductViewModel model)
        {
            try
            {
                int res = await _unitOfWork.Product.Delete(model.Product);
                if (res == 0) TempData["Error"] = $"{model.Product.Name} - Product didn't Deleted";
                else TempData["Success"] = $"{model.Product.Name} - Product Deleted";
                return RedirectToAction("Manage");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }

        #region Image Upload Logic
        private async Task<string> UploadedFile(ProductViewModel model)
        {
            string uniqueFileName = string.Empty;

            if (model.PhotoFile != null)
            {
                string uploadsFolder = Path.Combine(_web.WebRootPath, "images/products");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.PhotoFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.PhotoFile.CopyTo(fileStream);
                }
            }
            else
            {
                var currectProduct = await _unitOfWork.Product.Find(model.Product.Id);
                uniqueFileName = currectProduct.ImageUrl;
            }

            return uniqueFileName;
        }
        #endregion

    }
}

ShoppingCart/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCartInterfaces.IUnitOfWork;
using ShoppingCartModels.DbModels;
using ShoppingCartModels.ViewModels;
using ShoppingCartRepository.UnitOfWork;
using ShoppingCartUtilities.WebUtils;

namespace ShoppingCart.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Manage()
        {
            try
            {
                UserViewModel model = new UserViewModel
                {
                    Users = await Task.Run(()=> _unitOfWork.User.Get().Result
                                                .OrderByDescending(x => x.IsApproved).ToList())
                };
                return View(model);
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Manage");
            }
        }

        [HttpGet]
        public IActionResult Login()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Login(AdminUser user)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(user.Username) || string.IsNullOrWhiteSpace(user.Password)) TempData["Error"] = "Username/Password Cant be empty";
                var findUser = await _unitOfWork.User.Login(user.Username, user.Password);
                if(findUser == null)
                {
                    TempData["Error"] = "User Not found";
                    return RedirectToAction("Login");
                }
                else if(findUser != null && findUser.IsApproved == false)
                {
                    TempData["Error"] = "User Not approved yet";
                    return RedirectToAction("Login");
                }
                TempData["Success"] = "User logged in successfully";                
                return RedirectToAction("Dashboard","Home");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Login");
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Register");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Register(AdminUser user)
        {
            try
            {
                TempData["Error"] = FunctionForErrors.RegisterPageErrorValidation(user);
                if (TempData["Error"] != null) return RedirectToAction("Register");

                var resUser = await _unitOfWork.User.CreateUser(user);
                if (resUser == null)  TempData["Success"] = "User Created Successfully";
                else TempData["Error"] = "User Already Exists";
                return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Register");
            }
        }
    }
}

ShoppingCart/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taanka Official</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Dashboard">Taanka Official - Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end bg-dark text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header bg-dark">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Taanka Official - Admin</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-area="Admin" asp-controller="Home" asp-action="Dashboard">Home - Dashboard</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="User" asp-action="Manage">User Audit Management</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="Product" asp-action="Manage">Products Management</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="Category" asp-action="Manage">Categories Management</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="Order" asp-action="Manage">Order Management</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="Settings" asp-action="AppSettings">App Settings</a>
                            </li>
                        </ul>                       
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <main>
        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </main>

    <footer class="fixed-bottom footer">
        <div class="container text-center text-bg-dark">
            &copy; 2023 - Taanka Official - <a class="text-bg-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShoppingCart/Areas/Admin/Views/Shared/_MinimalLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taanka Official</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Taanka Official - Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end bg-dark text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header bg-dark">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Taanka Official - Admin</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="~/Home/Dashboard">Home - Dashboard</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="User" asp-action="Manage">User Audit Management</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="Product" asp-action="Manage">Products Management</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                   asp-area="Admin" asp-controller="Category" asp-action="Manage">Categories Management</a>
                            </li>
                        </ul>                       
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_Notification">
    </div>
    <main>
        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </main>

    <footer class="fixed-bottom footer">
        <div class="container text-center text-bg-dark">
            &copy; 2023 - Taanka Official - <a class="text-bg-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>